### ISSUE TITLE
Expose .len()

### ISSUE THREAD

**Issue by kpcyrd** [stusmall/ttl_cache#4]
I was about to write a PR that returns the number of entries, while reading through the source I discovered this method already exists :)

```
// This isn't made pubic because the length returned isn't exact. It can include expired values.
// If people find that they want this then I can include a length method that trims expired
// entries then returns the size, but I'd rather now.  One wouldn't expect a len() operation
// to change the contents of the structure.
```

The `.len()` method is still useful if somebody tries to calculate the amount of memory that is used by the cache, for an "accurate" number that doesn't include expired keys it might make sense to introduce `.count()` and document that this operation is expensive.

**Comment by stusmall** [comment]
There is a discussion on this feature in the referenced PR.  I'm going to close this out because this feature might cause problems for some people.  Adding len() to this structure has the potential of being O(n) which would be surprisingly to most devs.  There are other ways to get what @kpcyrd wanted
